apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-test
  labels:
    app: webapp-test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp-test
  template:
    metadata:
      labels:
        app: webapp-test
    spec:
      containers:
        - name: webapp-test
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: APP_COLOR
              value: {{ .Values.appColor | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
