# Global settings for all ArgoCD Applications
global:
  repoURL: https://github.com/csalwasser/webapp-test
  targetRevision: HEAD

# Application configurations
applications:
  webapp-color:
    enabled: true
    project: default
    namespace: webapp-test
